# =====================================================================
# Configuración de SonarQube para ms-gastos-comunes (Convivo)
# =====================================================================

sonar.projectKey=convivo_ms-gastos-comunes
sonar.projectName=Convivo - MS Gastos Comunes
sonar.projectVersion=0.1.0

sonar.sources=src/main/java,src/main/resources
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/.scannerwork/**

sonar.host.url=http://localhost:9000
