-- ms-gastos-comunes: esquema inicial (Oracle).
-- Ejecutado por Flyway solo en el perfil 'aws' (ver application-aws.yml,
-- spring.flyway.enabled=true). El perfil 'local' usa H2 con
-- hibernate.ddl-auto=update y no corre estas migraciones.

CREATE TABLE gastos_comunes (
    id                   NUMBER(19)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    unidad_id            VARCHAR2(64)    NOT NULL,
    concepto             VARCHAR2(200)   NOT NULL,
    monto                NUMBER(12,2)    NOT NULL,
    saldo_pendiente      NUMBER(12,2)    NOT NULL,
    estado               VARCHAR2(20)    NOT NULL,
    origen               VARCHAR2(20)    NOT NULL,
    referencia_externa   VARCHAR2(100),
    fecha_vencimiento    DATE,
    fecha_creacion       TIMESTAMP       NOT NULL,
    fecha_actualizacion  TIMESTAMP,
    version_optimista    NUMBER(19)
);

CREATE INDEX idx_gastos_comunes_unidad ON gastos_comunes (unidad_id);
CREATE INDEX idx_gastos_comunes_origen_ref ON gastos_comunes (origen, referencia_externa);

CREATE TABLE pagos (
    id              NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    gasto_comun_id  NUMBER(19)     NOT NULL,
    monto           NUMBER(12,2)   NOT NULL,
    metodo          VARCHAR2(20)   NOT NULL,
    usuario_sub     VARCHAR2(100)  NOT NULL,
    comprobante     VARCHAR2(200),
    fecha_pago      TIMESTAMP      NOT NULL,
    CONSTRAINT fk_pagos_gasto_comun FOREIGN KEY (gasto_comun_id) REFERENCES gastos_comunes (id)
);

CREATE INDEX idx_pagos_gasto_comun ON pagos (gasto_comun_id);

-- Patrón Outbox: eventos salientes (ej. gasto_fallido de compensación),
-- publicados de forma confiable por OutboxRelayScheduler.
CREATE TABLE outbox_eventos (
    id                 NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_id           VARCHAR2(64)   NOT NULL,
    exchange           VARCHAR2(100)  NOT NULL,
    routing_key        VARCHAR2(100)  NOT NULL,
    tipo               VARCHAR2(80)   NOT NULL,
    payload            CLOB           NOT NULL,
    estado             VARCHAR2(20)   NOT NULL,
    intentos           NUMBER(5)      NOT NULL,
    fecha_creacion     TIMESTAMP      NOT NULL,
    fecha_publicacion  TIMESTAMP,
    CONSTRAINT uq_outbox_event_id UNIQUE (event_id)
);

CREATE INDEX idx_outbox_estado ON outbox_eventos (estado, fecha_creacion);

-- Patrón Inbox: idempotencia de eventos entrantes (ej. reserva_espacio_creada).
CREATE TABLE inbox_eventos (
    event_id         VARCHAR2(64)  PRIMARY KEY,
    tipo             VARCHAR2(80)  NOT NULL,
    fecha_procesado  TIMESTAMP     NOT NULL
);
