name: Publicar imagen docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el codigo fuente del repositorio
        uses: actions/checkout@v7

      - name: Iniciar sesion en Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/ms-gastos-comunes:latest

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        continue-on-error: true
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Actualizar servicio en ECS Fargate
        continue-on-error: true
        run: |
          aws ecs update-service \
            --cluster convivo-cluster \
            --service convivo-ms-gastos-comunes \
            --force-new-deployment \
            --region us-east-1